site_name: Performance Hacks
site_author: 'zhoujiagen@gmail.com'
copyright: MIT
repo_name: perf_hacks
repo_url: https://github.com/zhoujiagen/perf_hacks

nav:
    - Home: index.md
    - Rust:
      - Home: rust/docs/index.md
      - 'Notes': rust/docs/notes.md
      - 'Tools': rust/docs/tool.md
    - 'Concurrency':
      - Home: concurrency/docs/index.md
      - 'TAMP':
        - 'Home': concurrency/docs/tamp/index.md
        - '1. Introduction': concurrency/docs/tamp/01-introduction.md
        - '2. Mutual Exclusion': concurrency/docs/tamp/02-mutual-exclusion.md
        - '3. Concurrent Objects': concurrency/docs/tamp/03-concurrent-objects.md
        - '4. Foundations of Shared Memory': concurrency/docs/tamp/04-foundations-of-shared-memory.md
        - '5. The Relative Power of Primitive Synchronization Operations': concurrency/docs/tamp/05-the-relative-power-of-primitive-synchronization-operations.md
        - '6. Universality of Consensus': concurrency/docs/tamp/06-universality-of-consensus.md
        - '7. Spin Locks and Contention': concurrency/docs/tamp/07-spin-locks-and-contention.md
        - '8. Monitors and Blocking Synchronization': concurrency/docs/tamp/08-monitors-and-blocking-synchronization.md
        - '9. Linked Lists': concurrency/docs/tamp/09-linked-lists.md
        - '10. Concurrent Queues and the ABA Problem': concurrency/docs/tamp/10-concurrent-queues-and-the-aba-problem.md
        - '11. Concurrent Stacks and Elimination': concurrency/docs/tamp/11-concurrent-stacks-and-elimination.md
        - '12. Counting, Sorting, and Distributed Coordination': concurrency/docs/tamp/12-counting-sorting-and-distributed-coordination.md
        - '13. Concurrent Hashing and Natural Parallelism': concurrency/docs/tamp/13-concurrent-hashing-and-natural-parallelism.md
        - '14. Skiplists and Balanced Search': concurrency/docs/tamp/14-skiplists-and-balanced-search.md
        - '15. Priority Queues': concurrency/docs/tamp/15-priority-queues.md
        - '16. Futures, Scheduling, and Work Distribution': concurrency/docs/tamp/16-futures-scheduling-and-work-distribution.md
        - '17. Barriers': concurrency/docs/tamp/17-barriers.md
        - '18. Transactional Memory': concurrency/docs/tamp/18-transactional-memory.md
      - 'Java Concurrency': concurrency/docs/java-concurrency.md
    - 'Performance Analysis':
      - 'Introduction': perf_analysis/docs/index.md
      - 'Terminology': perf_analysis/docs/terms.md
      - 'Tracing':
        - 'Linux Tracing Technologies': perf_analysis/docs/tracing/linux-tracing.md
        - 'Probes':
          - 'Tracepoint': perf_analysis/docs/tracing/probes/tracepoint.md
          - 'usdt': perf_analysis/docs/tracing/probes/usdt.md
          - 'kprobe, kretprobe': perf_analysis/docs/tracing/probes/kprobe.md
          - 'uprobe, uretprobe': perf_analysis/docs/tracing/probes/uprobe.md
          - 'software, hardware': perf_analysis/docs/tracing/probes/software_hardware.md
          - 'profile, interval': perf_analysis/docs/tracing/probes/profile_interval.md
        - 'Distributed Tracing':
          - 'OpenTracing': perf_analysis/docs/distributed_tracing/opentracing.md
          - 'Jaeger': perf_analysis/docs/distributed_tracing/jaeger.md
      - 'Tools':
        - 'perf': perf_analysis/docs/tools/perf.md
        - 'strace': perf_analysis/docs/tools/strace.md
        - 'BPF':
          - 'BCC': perf_analysis/docs/tools/bpf/bcc.md
          - 'bpftrace': perf_analysis/docs/tools/bpf/bpftrace.md
        - 'Flame Graph': perf_analysis/docs/flame-graph.md
      - 'Topics':
        - 'CPU': perf_analysis/docs/topics/perf-cpu.md
        - '内存': perf_analysis/docs/topics/perf-memory.md
        - '文件系统': perf_analysis/docs/topics/perf-file-system.md
        - '磁盘': perf_analysis/docs/topics/perf-disk.md
        - '网络': perf_analysis/docs/topics/perf-network.md
        - '安全': perf_analysis/docs/topics/perf-security.md
        - '语言': perf_analysis/docs/topics/perf-language.md
        - '应用': perf_analysis/docs/topics/perf-application.md
        - '内核': perf_analysis/docs/topics/perf-kernel.md
        - '虚拟化': perf_analysis/docs/topics/perf-virtual.md

#theme: readthedocs
theme:
  name: material
extra:
  search:
    language: 'en'
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
      guess_lang: False
  - toc:
      permalink: true
  - pymdownx.arithmatex # LaTeX math equations
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - footnotes
  - markdown_inline_graphviz

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
