site_name: Performance Hacks
site_author: 'zhoujiagen@gmail.com'
copyright: MIT
repo_name: perf_hacks
repo_url: https://github.com/zhoujiagen/perf_hacks

nav:
    - Home: index.md
    - Rust:
      - Home: rust/docs/index.md
      - 'Notes': rust/docs/notes.md
      - 'Tools': rust/docs/tool.md
    - 'Concurrency':
      - Home: concurrency/docs/index.md
      - 'TAMP': concurrency/docs/index.md
      - 'Java Concurrency': concurrency/docs/java-concurrency.md
    - 'Performance Analysis':
      - 'Introduction': perf_analysis/docs/index.md
      - 'Terminology': perf_analysis/docs/terms.md
      - 'Tracing':
        - 'Linux Tracing Technologies': perf_analysis/docs/tracing/linux-tracing.md
        - 'Probes':
          - 'Tracepoint': perf_analysis/docs/tracing/probes/tracepoint.md
          - 'usdt': perf_analysis/docs/tracing/probes/usdt.md
          - 'kprobe, kretprobe': perf_analysis/docs/tracing/probes/kprobe.md
          - 'uprobe, uretprobe': perf_analysis/docs/tracing/probes/uprobe.md
          - 'software, hardware': perf_analysis/docs/tracing/probes/software_hardware.md
          - 'profile, interval': perf_analysis/docs/tracing/probes/profile_interval.md
        - 'Distributed Tracing':
          - 'OpenTracing': perf_analysis/docs/distributed_tracing/opentracing.md
          - 'Jaeger': perf_analysis/docs/distributed_tracing/jaeger.md
      - 'Tools':
        - 'perf': perf_analysis/docs/tools/perf.md
        - 'strace': perf_analysis/docs/tools/strace.md
        - 'BPF':
          - 'BCC': perf_analysis/docs/tools/bpf/bcc.md
          - 'bpftrace': perf_analysis/docs/tools/bpf/bpftrace.md
        - 'Flame Graph': perf_analysis/docs/flame-graph.md
      - 'Topics':
        - 'CPU': perf_analysis/docs/topics/perf-cpu.md
        - '内存': perf_analysis/docs/topics/perf-memory.md
        - '文件系统': perf_analysis/docs/topics/perf-file-system.md
        - '磁盘': perf_analysis/docs/topics/perf-disk.md
        - '网络': perf_analysis/docs/topics/perf-network.md
        - '安全': perf_analysis/docs/topics/perf-security.md
        - '语言': perf_analysis/docs/topics/perf-language.md
        - '应用': perf_analysis/docs/topics/perf-application.md
        - '内核': perf_analysis/docs/topics/perf-kernel.md
        - '虚拟化': perf_analysis/docs/topics/perf-virtual.md

#theme: readthedocs
theme:
  name: material
extra:
  search:
    language: 'en'
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
      guess_lang: False
  - toc:
      permalink: true
  - pymdownx.arithmatex # LaTeX math equations
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - footnotes
  - markdown_inline_graphviz

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
