site_name: Performance Hacks
site_author: 'zhoujiagen@gmail.com'
copyright: MIT
repo_name: perf_hacks
repo_url: https://github.com/zhoujiagen/perf_hacks

nav:
  - 'Introduction': index.md
  - 'Terminology': terms.md
  - 'Tracing':
    - 'Linux Tracing Technologies': tracing/linux-tracing.md
    - 'Probes':
      - 'Tracepoint': tracing/probes/tracepoint.md
      - 'usdt': tracing/probes/usdt.md
      - 'kprobe, kretprobe': tracing/probes/kprobe.md
      - 'uprobe, uretprobe': tracing/probes/uprobe.md
      - 'software, hardware': tracing/probes/software_hardware.md
      - 'profile, interval': tracing/probes/profile_interval.md
    - 'Distributed Tracing':
      - 'Concepts': distributed_tracing/distributed-tracing-concepts.md
      - 'OpenTracing': distributed_tracing/opentracing.md
      - 'Jaeger': distributed_tracing/jaeger.md
  - 'Tools':
    - 'perf': tools/perf.md
    - 'strace': tools/strace.md
    - 'BPF':
      - 'BCC': tools/bpf/bcc.md
      - 'bpftrace': tools/bpf/bpftrace.md
    - 'Flame Graph': flame-graph.md
  - 'Topics':
    - 'CPU': topics/perf-cpu.md
    - '内存': topics/perf-memory.md
    - '文件系统': topics/perf-file-system.md
    - '磁盘': topics/perf-disk.md
    - '网络': topics/perf-network.md
    - '安全': topics/perf-security.md
    - '语言': topics/perf-language.md
    - '应用': topics/perf-application.md
    - '内核': topics/perf-kernel.md
    - '虚拟化': topics/perf-virtual.md

#theme: readthedocs
theme:
  name: material
extra:
  search:
    language: 'en'
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
      guess_lang: False
  - toc:
      permalink: true
  - pymdownx.arithmatex # LaTeX math equations
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
